CREATE TABLE IF NOT EXISTS ratings (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT ratings_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS FILMS (
	ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"NAME" varchar(50) NOT NULL,
	DESCRIPTION varchar(500) NOT NULL,
	RELEASEDATE varchar(50),
	DURATION integer,
	RATING_ID integer,
	CONSTRAINT films_pk PRIMARY KEY (id)
);

ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS films_ratings_fk FOREIGN KEY (rating_id) REFERENCES ratings(id);

CREATE TABLE IF NOT EXISTS genre_names (
	id integer NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT genres_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS films_genres (
	film_id integer NOT NULL,
	genre_id integer NOT NULL,
	CONSTRAINT films_genres_pk PRIMARY KEY (film_id, genre_id)
);

ALTER TABLE films_genres ADD CONSTRAINT IF NOT EXISTS films_genres_films_fk FOREIGN KEY (film_id) REFERENCES films(id);
ALTER TABLE films_genres ADD CONSTRAINT IF NOT EXISTS films_genres_genre_names_fk FOREIGN KEY (genre_id) REFERENCES genre_names(id);

CREATE TABLE IF NOT EXISTS users (
	id integer GENERATED BY DEFAULT AS IDENTITY,
	email varchar(50) NOT NULL,
	login varchar(50) NOT NULL,
	"name" varchar(50),
	birthday date,
	CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes (
	film_id integer NOT NULL,
	user_id integer NOT NULL,
	CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id)
);

ALTER TABLE likes ADD CONSTRAINT  IF NOT EXISTS likes_films_fk FOREIGN KEY (film_id) REFERENCES films(id);
ALTER TABLE likes ADD CONSTRAINT IF NOT EXISTS likes_users_fk FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE IF NOT EXISTS friends (
	user_id integer NOT NULL,
	friend_id integer NOT NULL,
	friendship_confirmed varchar(50) NOT NULL,
	CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id),
	CONSTRAINT check_cPol CHECK (friendship_confirmed IN ('yes', 'no'))
);

ALTER TABLE friends ADD CONSTRAINT IF NOT EXISTS friends_users_fk FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE friends ADD CONSTRAINT IF NOT EXISTS friends_users_fk_1 FOREIGN KEY (friend_id) REFERENCES users(id);